#-------------------------------
# Site Settings
title: Fully Modulated 
description: Fully Modulated is a podcast and blog that covers radio, broadcasting technology, industry news, and audio engineering topics.
logo: /logo.png # You can add own logo. For example '/images/logo.png'.
logo_dark: /logo.png


#-------------------------------
# Color Scheme Settings
color_scheme:
  default: dark # Default theme applied on the first visit (options: "light" or "dark")
  toggle: false # Enable theme toggle

# Enables or disables the theme toggle functionality:
# - true: Users can switch between light and dark modes using a toggle button.
#          The site will remember their choice for future visits.
# - false: The theme will always use the default mode specified above,
#          and the toggle button will not be displayed.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Episodes'
      url: 'tags/?tag=episodes'
    - title: 'Blog'
      url: 'tags/?tag=blog'      
    - title: 'Archive'
      url: '/archive/'
    - title: 'Pages'
      submenu:
      - url: '/about/'
        title: 'About'
      - url: '/contact/'
        title: 'Contact'


#-------------------------------
# Author Settings
author:
  author_name: Tyler Woodward
  author_avatar: images/tyler_profile.jpg


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_avatar: images/tyler_profile.jpg
  hero_title: Hi! Iâ€™m Tyler ðŸ‘‹
  hero_subtitle: Broadcast Network Engineer, Linux Advocate, Audiophile
  hero_description: "I am Tyler Woodward, a broadcast network engineer and audiophile from western Wisconsin who loves technology, Linux, and the open source world. Here you will find my thoughts, tips, and new episodes of The Tyler Woodward Project *(formerly Fully Modulated)*, where I talk about broadcasting, cybersecurity, data privacy, telecommunications, and the tech I am constantly experimenting with."
  hero_image: /images/network-cables.jpg
  hero_image_caption: Wired for possibility-A symphony of connections in perfect harmony
  hero_button_text: Connect With Me
  hero_button_link: '/contact/'


# Logos
logos:
  enable: true
  logos_title: Nerd Stuff
  logo_image:
    - alt: "Modulation"
      image: "/images/mod.jpg"
    - alt: "Microphones"
      image: "/images/mic.jpg"
    - alt: "Networking"
      image: "/images/network.jpg"
    - alt: "Towers"
      image: "/images/tower.jpg"
    - alt: "Linux"
      image: "/images/linux.jpg"


#-------------------------------
# Section Blog Settings
blog:
  enable: true
  blog_title: The Binary Journal


#-------------------------------
# Tags Section Settings
tags_section:
  enable: true
  tags_section_title: Network Operations Center
  tags:
    - tag: "Engineering"
      image: "/images/engineering.jpg"
    - tag: "Programming"
      image: "/images/dan-lefebvre-TV7HJIRjMiY-unsplash.jpg"
    - tag: "Tools"
      image: "/images/anton-savinov-lDwKKjlHL2Y-unsplash.jpg"
    - tag: "Episodes"
      image: "/images/igor-omilaev-kmJ8x-KNtyo-unsplash.jpg"
    - tag: "Wireless"
      image: "/images/justin-zhu-fGcSWTQZN2E-unsplash.jpg"
    - tag: "Tips"
      image: "/images/junior-ferreira-7esRPTt38nI-unsplash.jpg"
    - tag: "Industry"
      image: "/images/j-schiemann-xVtQtLiHwAA-unsplash.jpg"

#-------------------------------
# Videos Section Settings
videos_section:
  enable: true
  videos_section_title: Latest Episodes


#-------------------------------
# Gallery Section Settings
gallery_section:
  enable: true
  gallery_section_title: Bits and Bytes
  gallery:
    gallery_images:
      - alt: 'Rest'
        url: '/images/wire-tray.jpg'
        caption: 'Wires at work, sparking the magic of connection'
      - alt: 'Lifestyle'
        url: '/images/thomas-jensen-h3vT1Kp0FxA-unsplash.jpg'
        caption: 'Unifying networks with elegant, powerful simplicity'
      - alt: 'Hobby'
        url: '/images/marty-o-neill-Y7H5ZKUZsg8-unsplash.jpg'
        caption: 'Voice alive, commanding the airwaves with passion'
      - alt: 'Computers'
        url: '/images/pi.jpg'
        caption: 'Tiny circuits, big possibilities.'
      - alt: 'Games'
        url: '/images/christina-telep-6QzoMt1F6Sc-unsplash.jpg'
        caption: 'Steel sentinels broadcasting dreams across endless horizons'


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: true
  mailchimp_title: Stay Tuned Weekly ðŸ“»
  mailchimp_description: Every Sunday, I broadcast crisp, high-fidelity tips for leveling up your workflowâ€”straight from the studio to your inbox! Expect exclusive insights on radio tech, behind-the-scenes TV secrets, and hot networking hacks, plus sonic inspiration to keep your signals strong.
  mailchimp_identifier: fullymodulated.us8.list-manage.com/subscribe/post?u=164510d86f4d3932a4fc37786&amp;id=d9e3b3a2d9&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address...
  mailchimp_button_text: Subscribe to the Signal


#-------------------------------
# Footer Settings
footer_description: A broadcast network engineer, exploring broadcasting, cybersecurity, data privacy, telecommunications, and tech on The Tyler Woodward Project.


#-------------------------------
# Social Settings
social:
- {icon: "fa-solid fa-podcast", name: "Apple Podcasts", link: "https://podcasts.apple.com/podcast/id1803865840"}
- {icon: "fa-brands fa-spotify", name: "Spotify", link: "https://open.spotify.com/show/3yITnZVToJsnKpU04ma4at"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://www.instagram.com/tylerwoodward.me"}
- {icon: "fa-brands fa-threads", name: "Threads", link: "https://www.threads.com/@tylerwoodward.me"}
- {icon: "fa-brands fa-bluesky", name: "Threads", link: "https://bsky.app/profile/tylerwoodward.me"}
- {icon: "fa-solid fa-rss", name: "RSS", link: "feed.xml"}

# Example of adding a new link to the sidebar and footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
contact:
  form_id: xvgvogjj # Add your form_id
  button_text: Send Now

# NOTE
# Coderon theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus_identifier: fully-modulated # Add your shortname for Disqus Comment. For example anvod-studio-test
  disqus_title: Get On The Air
  disqus_button_text: Show Comments


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id